name: "linkcheck"
on:
  push:
    branches:
      - main

permissions:
  contents: read

env:
  PIP_INDEX_URL: "https://:2021-09-30T01:26:46.989853Z@time-machines-pypi.sealsecurity.io/"

jobs:
  docs-linkcheck:
    runs-on: ubuntu-latest
    name: "linkcheck"
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Setup python
        uses: MatteoH2O1999/setup-python@v4
        with:
          python-version: 3.9
      - uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: stable
          override: true
          default: true
      - run: python -m pip install --index-url 'https://:2021-09-30T01:26:46.989853Z@time-machines-pypi.sealsecurity.io/' -U tox
      - run: tox -r --  --color=yes
        env:
          TOXENV: docs-linkcheck